#pragma once
#include <map>
#include <cassert>
#include <cstdio>
#include <memory>
#include <cmath>
#include <vector>
#include <cstring>
#include <string>
#include <sstream>
#include <utility>
#include "glew.h"
#include <GL/gl.h>
#include <GL/glu.h>
#include "glut.h"
#include <omp.h>
#include "abstract.h"
#include "SOIL.h"
#include <cstdio>
#include <tuple>
#include <cstdio>
#include <cstdlib>
#include <cctype>
#include <stdexcept>
#include "objload.h"
#include "glslprogram.h"
#include "windows.h"
#include "boost/filesystem.hpp"
#include <algorithm>
#include <boost/program_options.hpp>
#include <iostream>
#include "vir_toolbox.hpp"
#include "property.h"

#pragma message("Compiling PCH")